version: '3.8'

volumes:
    db:
        name: db

services:
    app:
        build: 
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        ports:
            - 80:80
        depends_on:
            mysql.localhost:
                condition: service_healthy

    mysql.localhost:
        image: mariadb
        hostname: db
        env_file:
            - .env
        volumes:
            - db:/var/lib/mysql:Z
            - ./sql:/docker-entrypoint-initdb.d:Z
        healthcheck:
            test: mariadb --password=$$MARIADB_ROOT_PASSWORD -e 'show databases'
            interval: 30s
            timeout: 5s
            retries: 10